export const USERNAME_CHANGE = "USERNAME_CHANGE"; 
export const PASSWORD_CHANGE = "PASSWORD_CHANGE"; 
export const AUTH_SUCCESS = "AUTH_SUCCESS"; 
export const AUTH_FAIL = "AUTH_FAIL"; 
export const SHOW_LOADING = "SHOW_LOADING"; 
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"; 
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"; 
export const SET_INITIAL_STATE = "SET_INITIAL_STATE"; 
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE"; 


